services:
  mongodb:
    image: mongo:latest
    container_name: aaventure-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=aaventure
    restart: unless-stopped

volumes:
  mongodb_data:
